server:
    address: 0.0.0.0
    #context-path: /beerhouse
    port: 8099
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://sql177.main-hosting.eu/u765057031_assemblydb
    username: u765057031_root
    password: Support123
  jpa:
    #hibernate.ddl-auto: update
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    
search:
  configuration:
    default-limit: 20
    accept-range: 100
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://root:qwe123@cluster0.n31n2.mongodb.net/AssemblyVoting?retryWrites=true&w=majority

#kafka:
#  bootstrap-address: ${KAFKA_SERVER_ADDRESS}
#  num-partitions: ${KAFKA_NUM_PARTITIONS}
#  num-replicas: ${KAFKA_NUM_REPLICAS}
#  audit:
#    bootstrap-address: ${KAFKA_AUDIT_ADDRESS}
#    topic: ${KAFKA_AUDIT_TOPIC}

#logging:
#  file: assembly-voting.log
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#  level:
#    root: ERROR
